routes/web.php
<?php

use App\Http\Controllers\AppNotificationController;
use App\Http\Controllers\AppProfileController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Compro\AboutController;
use App\Http\Controllers\Compro\ArticleController as ComproArticleController;
use App\Http\Controllers\Compro\ContentController as ComproContentController;
use App\Http\Controllers\Compro\PageController as ComproPageController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\Customer\InvoiceController as CustomerInvoiceController;
use App\Http\Controllers\Customer\PartnerController as CustomerPartnerController;
use App\Http\Controllers\Customer\ProductController as CustomerProductController;
use App\Http\Controllers\Customer\WithdrawalController as CustomerWithdrawalController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\Partner\CustomerController as PartnerCustomerController;
use App\Http\Controllers\Partner\InvoiceController as PartnerInvoiceController;
use App\Http\Controllers\Partner\ProductController as PartnerProductController;
use App\Http\Controllers\Partner\ReportController as PartnerReportController;
use App\Http\Controllers\Partner\WithdrawalController as PartnerWithdrawalController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UploaderController;
use App\Http\Controllers\WithdrawalController;
use App\Http\Controllers\SliderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Override Default Auth
Route::get('/login', fn () => redirect(route('app.login')))->name('login');
Route::get('/masuk', fn () => redirect(route('app.login')));
Route::get('/register', fn () => redirect(route('app.register')))->name('register');
Route::get('/daftar', fn () => redirect(route('app.register')));

Route::get('/atur-ulang-kata-sandi/{token}', [AuthController::class, 'resetPasswordView'])->name('password.reset'); //Helper route for fortify
// Admin
Route::group(['prefix' => '/admin', 'as' => 'admin.'], function () {
    Route::get('/masuk', [AuthController::class, 'adminLoginView'])->name('login');

    Route::group(['middleware' => ['auth', 'is_admin']], function () {
        Route::get('/', [DashboardController::class, 'admin'])->name('home');

        Route::group(['prefix' => '/profil', 'as' => 'profile.'], function () {
            Route::get('/', [ProfileController::class, 'index'])->name('index');
            Route::group(['prefix' => '/update', 'as' => 'update.'], function () {
                Route::put('/general', [ProfileController::class, 'updateGeneral'])->name('general');
                Route::put('/password', [ProfileController::class, 'updatePassword'])->name('password');
                Route::put('/avatar', [ProfileController::class, 'updateAvatar'])->name('avatar');
            });
        });

        Route::group(['prefix' => '/master', 'as' => 'master.'], function () {
            Route::get('/customer/search', [CustomerController::class, 'search'])->name('customers.search');
            Route::get('/partner/search', [PartnerController::class, 'search'])->name('partners.search');

            Route::get('customer/download', [CustomerController::class, 'download'])->name('customers.download');
            Route::apiResource('customer', CustomerController::class)->names('customers');
            Route::get('customer/password/generate', [CustomerController::class, 'generatePassword'])->name('customers.password.generate');
            Route::put('customer/password/{customer}', [CustomerController::class, 'updatePassword'])->name('customers.password');

            Route::apiResource('partner', PartnerController::class)->names('partners');
            Route::apiResource('produk', ProductController::class)->names('products');
            Route::apiResource('metode-pembayaran', PaymentMethodController::class)->names('payments');
        });

        Route::group(['prefix' => '/layanan', 'as' => 'services.'], function () {
            Route::apiResource('transaksi', InvoiceController::class)->names('transactions')->only(['index', 'show']);
            Route::apiResource('penarikan-saldo', WithdrawalController::class)->names('withdrawals')->only(['index', 'show']);
        });

        Route::group(['prefix' => '/laporan', 'as' => 'reports.'], function () {
            Route::any('/pengeluaran', [ReportController::class, 'expense'])->name('expenses');
            Route::any('/produk', [ReportController::class, 'product'])->name('products');
        });

        Route::group(['prefix' => '/company-profile', 'as' => 'compro.'], function () {
            Route::group(['prefix' => '/pengaturan', 'as' => 'settings.'], function () {
                Route::get('/', [SettingController::class, 'index'])->name('index');
                Route::group(['prefix' => '/update', 'as' => 'update.'], function () {
                    Route::put('/general', [SettingController::class, 'updateGeneral'])->name('general');
                    Route::put('/total', [SettingController::class, 'updateTotal'])->name('total');
                });
            });

            Route::apiResource('slider', SliderController::class)->names('sliders');
            Route::resource('/konten', ContentController::class)->names('contents')->except('show');
            Route::resource('/artikel', ArticleController::class)->names('articles')->except('show');

            Route::group(['prefix' => '/halaman', 'as' => 'pages.'], function () {
                Route::get('/{page}', [PageController::class, 'edit'])->name('edit');
                Route::put('/{page}', [PageController::class, 'update'])->name('update');
            });
        });
    });
});

// App
Route::group(['prefix' => '/app', 'as' => 'app.'], function () {
    Route::get('/', [DashboardController::class, 'app'])->name('home');
    Route::get('/masuk', [AuthController::class, 'appLoginView'])->name('login');
    Route::get('/daftar', [AuthController::class, 'appRegisterView'])->name('register');
    Route::get('/verifikasi', [AuthController::class, 'appVerifyView'])->name('verify');
    Route::get('/lupa-kata-sandi', [AuthController::class, 'forgotPasswordView'])->name('forgot-password');
    Route::post('/lupa-kata-sandi', [AuthController::class, 'sendRequestPasswordReset'])->name('forgot-password');
    Route::get('/atur-ulang-kata-sandi/{token}', [AuthController::class, 'resetPasswordView'])->name('reset-password');
    Route::put('/atur-ulang-kata-sandi', [AuthController::class, 'resetPassword'])->name('reset-password');

    // Route::get('/reset-password/{token}', function (string $token) {
    //     return view('auth.reset-password', ['token' => $token]);
    // })->middleware('guest')->name('password.reset');

    Route::post('/simpan-device-token', [AuthController::class, 'storeDeviceToken'])->name('store-device-token');
    Route::post('/masuk-otomatis', [AuthController::class, 'sessionLogin'])->name('auto-login');
    Route::view('/offline', 'laravelpwa::offline')->name('offline');

    Route::group(['prefix' => '/pemberitahuan', 'as' => 'notification.'], function () {
        Route::match(['get', 'post'], '/', [AppNotificationController::class, 'index'])->name('index');
        Route::get('/ke/{notification}', [AppNotificationController::class, 'goto'])->name('goto');
    });

    Route::group(['prefix' => '/customer', 'as' => 'customer.', 'middleware' => ['auth', 'is_customer']], function () {
        Route::group(['prefix' => '/konfirmasi-alamat', 'as' => 'address.'], function () {
            Route::get('/', [AppProfileController::class, 'confirmAddress'])->name('confirm');
            Route::put('/', [AppProfileController::class, 'updateAddress'])->name('update');
        });

        Route::group(['middleware' => 'must_fill_address'], function () {
            Route::get('/', [DashboardController::class, 'customer'])->name('home');

            Route::group(['prefix' => '/profil', 'as' => 'profile.'], function () {
                Route::get('/', [AppProfileController::class, 'index'])->name('index');
                Route::get('/ubah', [AppProfileController::class, 'edit'])->name('edit');
                Route::get('/ubah/kata-sandi', [AppProfileController::class, 'editPassword'])->name('password');
                Route::put('/ubah', [AppProfileController::class, 'update'])->name('update');
                Route::put('/ubah/kata-sandi', [AppProfileController::class, 'updatePassword'])->name('password');
            });

            Route::group(['prefix' => '/partner', 'as' => 'partner.'], function () {
                Route::get('/', [CustomerPartnerController::class, 'index'])->name('index');
                Route::post('/nearby', [CustomerPartnerController::class, 'nearby'])->name('nearby');
                Route::post('/change', [CustomerPartnerController::class, 'change'])->name('change');
            });

            Route::group(['middleware' => 'must_connected_with_partner'], function () {
                Route::group(['prefix' => '/produk', 'as' => 'products.'], function () {
                    Route::get('/', [CustomerProductController::class, 'index'])->name('index');

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PartnerRequest;
use App\Models\User;
use Error;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\View\View;

class PartnerController extends Controller
{
    /**
     * Handling route for list of partner and datatables
     *
     * @return View|JsonResponse
     */
    public function index(): View|JsonResponse
    {
        if (request()->ajax()) {
            $partners = User::withCount(['customers'])->where('role', 'partner');

            return datatables($partners)
                ->filter(function ($query) {
                    if (request()->has('search')) {
                        $query->where(function ($query) {
                            $query->where('phone', 'like', '%'.Str::replaceFirst('0', '', Str::replace('-', '', request('search.value'))).'%')
                                  ->orWhere('name', 'like', '%'.request('search.value').'%')
                                  ->orWhere('email', 'like', '%'.request('search.value').'%');
                        });
                    }
                })
                ->addIndexColumn()
                ->editColumn('avatar', 'datatables._avatar')
                ->editColumn('phone', function ($partner) {
                    return $partner->phone_converted;
                })
                ->editColumn('action', 'datatables._actions')
                ->rawColumns(['avatar', 'action'])
                ->toJson();
        }

        return view('admin.master.partners');
    }

    /**
     * Insert new partner
     *
     * @param  PartnerRequest  $request
     * @return JsonResponse
     */
    public function store(PartnerRequest $request): JsonResponse
    {
        try {
            DB::beginTransaction();
            User::buat($request->all());
            DB::commit();
            $http_code = 200;
            $response = $this->save_response();
        } catch (Exception $e) {
            DB::rollback();
            $http_code = $e->getCode() == 422 ? 422 : 421;
            $response = $this->error_msg($e);
        }

        return response()->json($response, $http_code);
    }

    /**
     * Show partner's detail
     *
     * @param  User  $partner
     * @return JsonResponse
     */
    public function show(User $partner): JsonResponse
    {
        try {
            if ($partner->role == 'partner') {
                $text_schedule = "<span class='badge bg-label-danger'>Belum Diatur</span>";

                if ($partner->schedule->count() > 0) {
                    $text_schedule = [];
                    if ($partner->schedule->monday) {
                        $text_schedule[] = 'Senin';
                    }
                    if ($partner->schedule->tuesday) {
                        $text_schedule[] = 'Selasa';
                    }
                    if ($partner->schedule->wednesday) {
                        $text_schedule[] = 'Rabu';
                    }
                    if ($partner->schedule->thursday) {
                        $text_schedule[] = 'Kamis';
                    }
                    if ($partner->schedule->friday) {
                        $text_schedule[] = 'Jumat';
                    }
                    if ($partner->schedule->saturday) {
                        $text_schedule[] = 'Sabtu';
                    }
                    if ($partner->schedule->sunday) {
                        $text_schedule[] = 'Minggu';
                    }
                    $text_schedule = implode(', ', $text_schedule);
                }

                return response()->json([
                    'avatar' => $partner->avatar,
                    'avatar_link' => $partner->avatar_link,
                    'name' => $partner->name,
                    'email' => $partner->email,
                    'phone' => $partner->phone ?? '',
                    'phone_converted' => $partner->phone_converted ?? '',
                    'address' => $partner->address,
                    'latitude' => $partner->latitude,
                    'longitude' => $partner->longitude,
                    'customers' => ($partner->customers->map(fn ($customer) => ['name' => $customer->name, 'address' => $customer->address])->sortBy('name'))->values()->all(),
                    'total_customer' => $partner->customers->count(),
                    'schedules' => $partner->schedule,
                    'text_schedule' => $text_schedule,
                ]);
            }

            throw new Exception('partner not found', 404);
        } catch (Exception $e) {
            return  response()->json($e->getMessage(), ($e->getCode() != 0 ? $e->getCode() : 500));
        } catch (Error $e) {
            return  response()->json($e->getMessage(), ($e->getCode() != 0 ? $e->getCode() : 500));
        }
    }

    /**
     * Update partner's detail
     *
     * @param  PartnerRequest  $request
     * @param  User  $partner
     * @return JsonResponse
     */
    public function update(PartnerRequest $request, User $partner): JsonResponse
    {
        try {
            DB::beginTransaction();
            $partner->ubah($request->all(), true);
            DB::commit();
            $http_code = 200;
            $response = $this->update_response();
        } catch (Exception $e) {
            DB::rollback();
            $http_code = $e->getCode() == 422 ? 422 : 421;
            $response = $this->error_msg($e);
        }

        return response()->json($response, $http_code);
    }

    /**
     * Remove partner from the list
     *
     * @param  User  $partner
     * @return JsonResponse
     */
    public function destroy(User $partner): JsonResponse
    {
        try {
            DB::beginTransaction();
            $partner->hapus();
            DB::commit();
            $http_code = 200;
            $response = $this->delete_response();
        } catch (Exception $e) {
            DB::rollback();
            $http_code = $e->getCode() == 422 ? 422 : 421;
            $response = $this->error_msg($e);
        }

        return response()->json($response, $http_code);
    }

    /**
     * Search partner for select2
     *
     * @param  Request  $request
     * @return array
     */
    public function search(Request $request): array
    {
        $partners = User::select(['name', 'id'])
                        ->whereRole('partner')
                        ->where('name', 'like', '%'.$request->search.'%')
                        ->get()
                        ->map(function ($partner) {
                            return [
                                'id' => $partner->id,
                                'text' => $partner->name,
                            ];
                        })
                        ->toArray();

        return $partners;
    }
}

resources/views/app/partner/index.blade.php
@extends('layout.app.main', [
    'title' => 'Dasbor',
    'headerSticky' => '<img src="'.asset('images/assets/logo.png').'" style="width:100px">',
    'headerTop' => '<img src="'.asset('images/assets/logo.png').'" style="width:150px">',
])

@section('contents')
    <div class="card card-style gradient-grey">
        <div class="content">
            <div class="d-flex justify-content-between align-items-center px-2">
                <div>
                    <p class="mb-n1 opacity-70 font-600">Selamat datang,</p>
                    <div class="h1 fw-bold">{{ auth()->user()->name }}</div>
                </div>
            </div>
            <hr class="my-2">
            <div class="d-flex justify-content-between align-items-center px-2 gap-2">
                <div>
                    <p class="mb-n1 opacity-70 font-600">Nominal Sampah</p>
                    <div class="h1 fw-bold gradient-grass color-white rounded-s p-2 my-2">{{ Sirius::toRupiah($nominal) }}</div>
                </div>
                <div>
                    <p class="mb-n1 opacity-70 font-600">Berat Sampah</p>
                    <div class="h1 fw-bold gradient-grass color-white rounded-s p-2 my-2">{{ Str::replace(',0', '', number_format($weight, 1, ',', '.')).' kg' }}</div>
                </div>
            </div>
        </div>
    </div>

    <x-app-title>
        @slot('actions')
            <x-app-button color="bg-blue-dark" size="s" link="{{ route('app.partner.orders.index') }}"><i class="fa-solid fa-arrow-right font-15"></i></x-app-button>
        @endslot
        Pesanan Terkini
    </x-app-title>

    <div class="my-3">
        @forelse ($invoices as $invoice)
            <a href="{{ route('app.partner.orders.show', ['invoice' => $invoice->code]) }}">
                <x-app-card class="mb-3">
                    <div class="d-flex justify-content-between align-items-center mb-0">
                        <p class="fw-bold font-15 mb-0">Pesanan #{{ $invoice->code }}</p>
                        <p class="fw-bold opacity-70">{{ Sirius::toLongDate($invoice->created_at) }}</p>
                    </div>
                    <p class="mb-0 fw-bold text-{{ App\Models\Invoice::mappingCurrentStatusColor($invoice->current_status) }}">{{ $invoice->current_status_converted }}</p>
                    <p class="mb-0">Total Jenis: {{ $invoice->products->count() }} Jenis Sampah</p>
                    <p class="mb-0">Pelanggan: {{ $invoice->customer->name ?? "Customer Tidak Diketahui" }}</p>
                    <p class="mb-0">Alamat: {{ $invoice->address }}</p>
                </x-app-card>
            </a>
        @empty
            <div class="mx-3">
                <x-app-chip color="blue" icon="fa-solid fa-check-double" class="w-100">Semua pesanan telah selesai diproses.</x-app-chip>
            </div>
        @endforelse
    </div>

    <x-app-title class="mt-4">
        @slot('actions')
            <x-app-button color="bg-blue-dark" size="s" link="{{ route('app.partner.withdrawals.index') }}"><i class="fa-solid fa-arrow-right font-15"></i></x-app-button>
        @endslot
        Tarikan Saldo Terkini
    </x-app-title>

    <div class="my-3">
         @forelse ($withdrawals as $withdrawal)
            <a href="{{ route('app.partner.withdrawals.show', ['withdrawal' => $withdrawal->code]) }}">
                <x-app-card class="mb-3">
                    <div class="d-flex justify-content-between align-items-center mb-0">
                        <p class="fw-bold font-15 mb-0">Pesanan #{{ $withdrawal->code }}</p>
                        <p class="fw-bold opacity-70">{{ Sirius::toLongDate($withdrawal->created_at) }}</p>
                    </div>
                    <p class="mb-0 fw-bold text-{{ App\Models\Withdrawal::mappingCurrentStatusColor($withdrawal->current_status) }}">{{ $withdrawal->current_status_converted }}</p>
                    <p class="mb-0">Total Tunai: {{ Sirius::toRupiah($withdrawal->amount) }}</p>
                    <p class="mb-0">Pelanggan: {{ $withdrawal->customer->name }}</p>
                </x-app-card>
            </a>
        @empty
            <div class="mx-3">
                <x-app-chip color="blue" icon="fa-solid fa-check-double" class="w-100">Semua permintaan penarikan telah selesai diproses.</x-app-chip>
            </div>
        @endforelse
    </div>

@endsection

resources/views/app/partner/setting.blade.php
@extends('layout.app.main', ['title' => 'Pengaturan', 'back' => route('app.partner.profile.index')])

@section('contents')
    <x-app-form id="form-edit" method="put" class="pt-2">
        <x-app-title>Atur Jadwal Ambil</x-app-title>

        <div class="m-3">
            <x-app-button id="" size="s" color="bg-blue-dark" class="w-100" data-menu="sheet-day-taken">
                <div class="d-flex justify-content-between align-items-center">
                    <div id="showed-days">{{ implode(', ', auth()->user()->schedules_converted) }}</div>
                    <div><i class="fa-solid fa-caret-down"></i></div>
                </div>
            </x-app-button>
            <input type="hidden" name="schedule[monday]" value="{{ auth()->user()->schedule->monday ? 1 : 0 }}">
            <input type="hidden" name="schedule[tuesday]" value="{{ auth()->user()->schedule->tuesday ? 1 : 0 }}">
            <input type="hidden" name="schedule[wednesday]" value="{{ auth()->user()->schedule->wednesday ? 1 : 0 }}">
            <input type="hidden" name="schedule[thursday]" value="{{ auth()->user()->schedule->thursday ? 1 : 0 }}">
            <input type="hidden" name="schedule[friday]" value="{{ auth()->user()->schedule->friday ? 1 : 0 }}">
            <input type="hidden" name="schedule[saturday]" value="{{ auth()->user()->schedule->saturday ? 1 : 0 }}">
            <input type="hidden" name="schedule[sunday]" value="{{ auth()->user()->schedule->sunday ? 1 : 0 }}">
        </div>

        <x-app-title>Atur Produk</x-app-title>

        <p class="m-3 text-center color-green-dark">Masukkan harga per kilogramnya.</p>

        <div class="m-3 pb-1">

            <div id="selected-products">
                @foreach (auth()->user()->products as $product)
                    <div class="card card-style mb-1" style="overflow: unset">
                        <div class="content fw-bold">
                            <button type="button" class="btn rounded-xs text-uppercase font-700 shadow-s bg-red-dark remove-product" style="position: absolute; left: -13px; top: 32%; padding: 1px 4px" data-id="{{ $product->id }}">
                                <i class="fa-solid fa-minus"></i>
                            </button>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex justify-content-start align-items-center w-75">
                                    <img src="{{ $product->image_link }}" style="height: 35px; width: 35px; object-fit: cover;" class="mx-3" alt="Icon {{ $product->name }}">
                                    <p class="p-0">{{ $product->name }}</p>
                                </div>
                                <div class="">
                                    <input class="form-control to-rupiah text-end" value="{{ number_format($product->pivot->price, thousands_separator:'.') }}" name="products[{{ $product->id }}]">
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>

            <div class="text-center mt-4">
                <x-app-button size="s" color="bg-blue-dark" icon="fa-solid fa-plus" data-menu="sheet-products">Tambah Jenis</x-app-button>
            </div>

        </div>

        <div class="text-center mt-4 mb-3 mx-3">
            <x-app-button size="l" icon="fa-solid fa-paper-plane" class="w-100" type="submit">Simpan Perubahan</x-app-button>
        </div>
    </x-app-form>
@endsection

@section('sheets')
    <x-app-sheet id="sheet-day-taken" title="Pilih Hari">
        <x-app-list-group class="mx-3">
            @foreach (['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'] as $day)
                <div class="mb-2 border-bottom">
                    <div class="form-check icon-check">
                        <input class="form-check-input" type="checkbox" value="{{ $day }}" id="check-{{ $day }}" @checked(auth()->user()->schedule->$day)>
                        <label class="form-check-label" for="check-{{ $day }}">{{ Sirius::longDay(date('w', strtotime($day))) }}</label>
                        <i class="icon-check-1 far fa-square color-gray-dark font-16"></i>
                        <i class="icon-check-2 far fa-check-square font-16 color-highlight"></i>
                    </div>
                </div>
            @endforeach
        </x-app-list-group>
        <div class="m-3">
            <x-app-button class="mb-4 w-100 close-menu" id="select-day"><i class="fa-solid fa-check me-2"></i>Pilih</x-app-button>
        </div>
    </x-app-sheet>


    <x-app-sheet id="sheet-products" title="Tambah Jenis Sampah">
        <div class="me-4 ms-3 mt-2">
            <x-app-form method="post" id="form-search-products">
                <x-app-form-input id="search-products" class="mb-2" name="search" placeholder="Cari ..." >
                    @slot('subLabel')
                        <i class="fa-solid fa-search"></i>
                    @endslot
                </x-app-form-input>
            </x-app-form>
            <div class="list-group list-custom-small close-menu mb-4" id="products">

            </div>
        </div>
    </x-app-sheet>
@endsection

@push('js')
    <script>
        const days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']

        let products = {}
        let selectedProducts = @json(auth()->user()->products->pluck('id')->toArray())

        function documentReady() {
            $("#select-day").click(function () {
                let selected = [];
                days.forEach(day => {
                    if ($("#check-" + day).is(":checked")) {
                        $('input[name="schedule[' + day + ']"]').eq(0).val(1)
                        selected.push($("#check-" + day).parent().find('label').eq(0).html())
                    }
                    else {
                        $('input[name="schedule[' + day + ']"]').eq(0).val(0)
                    }
                });
                $("#showed-days").html(selected.join(', '))
            })

            $("#search-products").change(function () {
                $("#products").html(`
                    <div>
                        <i class="fa-solid fa-spin fa-circle-notch"></i><span class="d-inline-block ms-2">Sedang mencari ...</span>
                    </div>
                `)

                const data = new FormData(document.getElementById('form-search-products'))
                data.append('selected', JSON.stringify(selectedProducts))

                ajaxPost("{{ route('app.partner.products.search') }}", data, null, function (result) {
                    products = result.data
                    $("#products").html(``)

                    if (Object.keys(products).length > 0) {
                        $.each(products, function (index, product) {
                            $("#products").append(`
                                <div class="mb-2 border-bottom d-flex justify-content-between align-items-center product" data-id="` + product.id + `">
                                    <div><img class="me-3 mt-2" src="` + product.image + `"><span>` + product.name + `</span></div>
                                </div>
                            `)
                        })
                    } else {
                        $("#products").html(`Produk yang dicari tidak ditemukan.`)
                    }
                }, function (errorResponse) {
                    $("#products").html(`<x-app-chip color='red' icon="fa-solid fa-xmark">` + errorResponse.message + `</x-app-chip>`)
                }, false)
            })

            $("#search-products").change()

            $("#form-search-products").submit(function(e) {
                e.preventDefault()
            })

            $(document).on('click', '.product', function () {
                const id = $(this).data('id')
                const product = products[id]
                selectedProducts.push(id)

                $("#selected-products").append(`
                    <div class="card card-style mb-1" style="overflow: unset">
                        <div class="content fw-bold">
                            <button type="button" class="btn rounded-xs text-uppercase font-700 shadow-s bg-red-dark remove-product" data-id="` + product.id + `" style="position: absolute; left: -13px; top: 32%; padding: 1px 4px">
                                <i class="fa-solid fa-minus"></i>
                            </button>

                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex justify-content-start align-items-center w-75">
                                    <img src="` + product.image + `" style="height: 35px; width: 35px; object-fit: cover;" class="mx-3" alt="Icon ` + product.name + `">
                                    <p class="p-0">` + product.name + `</p>
                                </div>
                                <div class="">
                                    <input class="form-control to-rupiah text-end" value="` + product.price + `" name="products[` + product.id + `]">
                                </div>
                            </div>
                        </div>
                    </div>
                `)

                $(this).remove()
            })

            $(document).on('click', '.remove-product', function () {
                const id = $(this).data('id')
                selectedProducts.splice( $.inArray(id, selectedProducts), 1 );

                $(this).parent().parent().remove()
                $("#search-products").change()
            })

            $("#form-edit").submit(function (e) {
                e.preventDefault();

                loadingWithText("Menyimpan perubahan ...");

                const data = new FormData(document.getElementById('form-edit'));

                ajaxPost("{{ route('app.partner.profile.edit.setting') }}", data, null, function (result) {
                    Swal.fire({
                        title: "Pengaturan disimpan!",
                        icon: 'success',
                    })
                }, function (errorResponse) {
                    Swal.fire({
                        title: "Gagal menyimpan!",
                        icon: 'error',
                        text: errorResponse.message
                    })
                }, false)
            })
        }
    </script>
@endpush