routes/web.php
<?php

use App\Http\Controllers\AppNotificationController;
use App\Http\Controllers\AppProfileController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Compro\AboutController;
use App\Http\Controllers\Compro\ArticleController as ComproArticleController;
use App\Http\Controllers\Compro\ContentController as ComproContentController;
use App\Http\Controllers\Compro\PageController as ComproPageController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\Customer\InvoiceController as CustomerInvoiceController;
use App\Http\Controllers\Customer\PartnerController as CustomerPartnerController;
use App\Http\Controllers\Customer\ProductController as CustomerProductController;
use App\Http\Controllers\Customer\WithdrawalController as CustomerWithdrawalController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\Partner\CustomerController as PartnerCustomerController;
use App\Http\Controllers\Partner\InvoiceController as PartnerInvoiceController;
use App\Http\Controllers\Partner\ProductController as PartnerProductController;
use App\Http\Controllers\Partner\ReportController as PartnerReportController;
use App\Http\Controllers\Partner\WithdrawalController as PartnerWithdrawalController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UploaderController;
use App\Http\Controllers\WithdrawalController;
use App\Http\Controllers\SliderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Override Default Auth
Route::get('/login', fn () => redirect(route('app.login')))->name('login');
Route::get('/masuk', fn () => redirect(route('app.login')));
Route::get('/register', fn () => redirect(route('app.register')))->name('register');
Route::get('/daftar', fn () => redirect(route('app.register')));

Route::get('/atur-ulang-kata-sandi/{token}', [AuthController::class, 'resetPasswordView'])->name('password.reset'); //Helper route for fortify
// Admin
Route::group(['prefix' => '/admin', 'as' => 'admin.'], function () {
    Route::get('/masuk', [AuthController::class, 'adminLoginView'])->name('login');

    Route::group(['middleware' => ['auth', 'is_admin']], function () {
        Route::get('/', [DashboardController::class, 'admin'])->name('home');

        Route::group(['prefix' => '/profil', 'as' => 'profile.'], function () {
            Route::get('/', [ProfileController::class, 'index'])->name('index');
            Route::group(['prefix' => '/update', 'as' => 'update.'], function () {
                Route::put('/general', [ProfileController::class, 'updateGeneral'])->name('general');
                Route::put('/password', [ProfileController::class, 'updatePassword'])->name('password');
                Route::put('/avatar', [ProfileController::class, 'updateAvatar'])->name('avatar');
            });
        });

        Route::group(['prefix' => '/master', 'as' => 'master.'], function () {
            Route::get('/customer/search', [CustomerController::class, 'search'])->name('customers.search');
            Route::get('/partner/search', [PartnerController::class, 'search'])->name('partners.search');

            Route::get('customer/download', [CustomerController::class, 'download'])->name('customers.download');
            Route::apiResource('customer', CustomerController::class)->names('customers');
            Route::get('customer/password/generate', [CustomerController::class, 'generatePassword'])->name('customers.password.generate');
            Route::put('customer/password/{customer}', [CustomerController::class, 'updatePassword'])->name('customers.password');

            Route::apiResource('partner', PartnerController::class)->names('partners');
            Route::apiResource('produk', ProductController::class)->names('products');
            Route::apiResource('metode-pembayaran', PaymentMethodController::class)->names('payments');
        });

        Route::group(['prefix' => '/layanan', 'as' => 'services.'], function () {
            Route::apiResource('transaksi', InvoiceController::class)->names('transactions')->only(['index', 'show']);
            Route::apiResource('penarikan-saldo', WithdrawalController::class)->names('withdrawals')->only(['index', 'show']);
        });

        Route::group(['prefix' => '/laporan', 'as' => 'reports.'], function () {
            Route::any('/pengeluaran', [ReportController::class, 'expense'])->name('expenses');
            Route::any('/produk', [ReportController::class, 'product'])->name('products');
        });

        Route::group(['prefix' => '/company-profile', 'as' => 'compro.'], function () {
            Route::group(['prefix' => '/pengaturan', 'as' => 'settings.'], function () {
                Route::get('/', [SettingController::class, 'index'])->name('index');
                Route::group(['prefix' => '/update', 'as' => 'update.'], function () {
                    Route::put('/general', [SettingController::class, 'updateGeneral'])->name('general');
                    Route::put('/total', [SettingController::class, 'updateTotal'])->name('total');
                });
            });

            Route::apiResource('slider', SliderController::class)->names('sliders');
            Route::resource('/konten', ContentController::class)->names('contents')->except('show');
            Route::resource('/artikel', ArticleController::class)->names('articles')->except('show');

            Route::group(['prefix' => '/halaman', 'as' => 'pages.'], function () {
                Route::get('/{page}', [PageController::class, 'edit'])->name('edit');
                Route::put('/{page}', [PageController::class, 'update'])->name('update');
            });
        });
    });
});

// App
Route::group(['prefix' => '/app', 'as' => 'app.'], function () {
    Route::get('/', [DashboardController::class, 'app'])->name('home');
    Route::get('/masuk', [AuthController::class, 'appLoginView'])->name('login');
    Route::get('/daftar', [AuthController::class, 'appRegisterView'])->name('register');
    Route::get('/verifikasi', [AuthController::class, 'appVerifyView'])->name('verify');
    Route::get('/lupa-kata-sandi', [AuthController::class, 'forgotPasswordView'])->name('forgot-password');
    Route::post('/lupa-kata-sandi', [AuthController::class, 'sendRequestPasswordReset'])->name('forgot-password');
    Route::get('/atur-ulang-kata-sandi/{token}', [AuthController::class, 'resetPasswordView'])->name('reset-password');
    Route::put('/atur-ulang-kata-sandi', [AuthController::class, 'resetPassword'])->name('reset-password');

    // Route::get('/reset-password/{token}', function (string $token) {
    //     return view('auth.reset-password', ['token' => $token]);
    // })->middleware('guest')->name('password.reset');

    Route::post('/simpan-device-token', [AuthController::class, 'storeDeviceToken'])->name('store-device-token');
    Route::post('/masuk-otomatis', [AuthController::class, 'sessionLogin'])->name('auto-login');
    Route::view('/offline', 'laravelpwa::offline')->name('offline');

    Route::group(['prefix' => '/pemberitahuan', 'as' => 'notification.'], function () {
        Route::match(['get', 'post'], '/', [AppNotificationController::class, 'index'])->name('index');
        Route::get('/ke/{notification}', [AppNotificationController::class, 'goto'])->name('goto');
    });

    Route::group(['prefix' => '/customer', 'as' => 'customer.', 'middleware' => ['auth', 'is_customer']], function () {
        Route::group(['prefix' => '/konfirmasi-alamat', 'as' => 'address.'], function () {
            Route::get('/', [AppProfileController::class, 'confirmAddress'])->name('confirm');
            Route::put('/', [AppProfileController::class, 'updateAddress'])->name('update');
        });

        Route::group(['middleware' => 'must_fill_address'], function () {
            Route::get('/', [DashboardController::class, 'customer'])->name('home');

            Route::group(['prefix' => '/profil', 'as' => 'profile.'], function () {
                Route::get('/', [AppProfileController::class, 'index'])->name('index');
                Route::get('/ubah', [AppProfileController::class, 'edit'])->name('edit');
                Route::get('/ubah/kata-sandi', [AppProfileController::class, 'editPassword'])->name('password');
                Route::put('/ubah', [AppProfileController::class, 'update'])->name('update');
                Route::put('/ubah/kata-sandi', [AppProfileController::class, 'updatePassword'])->name('password');
            });

            Route::group(['prefix' => '/partner', 'as' => 'partner.'], function () {
                Route::get('/', [CustomerPartnerController::class, 'index'])->name('index');
                Route::post('/nearby', [CustomerPartnerController::class, 'nearby'])->name('nearby');
                Route::post('/change', [CustomerPartnerController::class, 'change'])->name('change');
            });

            Route::group(['middleware' => 'must_connected_with_partner'], function () {
                Route::group(['prefix' => '/produk', 'as' => 'products.'], function () {
                    Route::get('/', [CustomerProductController::class, 'index'])->name('index');

app/Http/Controllers/Customer/PartnerController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Http\Requests\AppChangePartnerRequest;
use App\Models\Invoice;
use App\Models\Notification;
use App\Models\User;
use App\Models\Withdrawal;
use Error;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\View\View;

class PartnerController extends Controller
{
    /**
     * Handle route to customer's partner
     *
     * @return View
     */
    public function index(): View
    {
        $isConnected = auth()->user()->partner_confirm_at ? true : false;
        $partner = auth()->user()->partner;

        $schedules = $partner->schedules_converted ?? [];
        $schedules = implode(', ', $schedules);

        return view('app.customer.partner', compact('partner', 'isConnected', 'schedules'));
    }

    /**
     * Searching nearby partner
     *
     * @param  Request  $request
     * @return JsonResponse
     */
    public function nearby(Request $request): JsonResponse
    {
        try {
            $result = auth()->user()
                            ->partner_terdekat($request)
                            ->when($request->search, function ($query) use ($request) {
                                $query->where(function ($query) use ($request) {
                                    $query->where('p.name', 'like', "%$request->search%")
                                        ->orWhere('p.address', 'like', "%$request->search%")
                                        ->orWhere('p.phone', 'like', '%'.Str::replaceFirst('0', '', Str::replace('-', '', $request->search)).'%');
                                });
                            })
                            ->simplePaginate($request->limit ?? 10)
                            ->withQueryString();

            $distances = $result->pluck('distance', 'id')->toArray();
            $result = $result->toArray();

            $order = explode('.', $request->order);
            $order = $order[count($order) - 1];
            $partners = User::with(['schedule', 'products'])
                            ->whereRole('partner')
                            ->find(array_keys($distances))
                            ->map(function ($partner) use ($distances) {
                                return [
                                    'id' => $partner->id,
                                    'name' => $partner->name,
                                    'address' => $partner->address,
                                    'distance' => round($distances[$partner->id]),
                                    'phone' => $partner->phone_converted,
                                    'schedules' => implode(', ', $partner->schedules_converted),
                                    'products' => implode(', ', $partner->products->pluck('name')->toArray()),
                                ];
                            })
                            ->when(($request->sort == 'asc'), function ($query) use ($order) {
                                return $query->sortBy($order);
                            })
                            ->when(($request->sort == 'desc'), function ($query) use ($order) {
                                return $query->sortByDesc($order);
                            })
                            ->values()->all();

            $result['data'] = $partners;

            $data = $this->apiResponse(true, 'OK', $result);
            $http_code = 200;
            if (empty($partners)) {
                $data = $this->apiResponse(false);
            }
        } catch (Exception $e) {
            // $data = $this->apiResponse(false, $e->getMessage());
            $data = $this->apiResponse(false, 'Terjadi masalah pada sistem, harap hubungi penyedia layanan Anda!');
            $http_code = $e->getCode() == 422 ? 422 : 421;
        } catch (Error $e) {
            // $data = $this->apiResponse(false, $e->getMessage());
            $data = $this->apiResponse(false, 'Terjadi masalah pada sistem, harap hubungi penyedia layanan Anda!');
            $http_code = $e->getCode() == 422 ? 422 : 421;
        }

        return  response()->json($data, $http_code);
    }

    /**
     * Changing customer's partner
     *
     * @param  AppChangePartnerRequest  $request
     * @return JsonResponse
     */
    public function change(AppChangePartnerRequest $request): JsonResponse
    {
        try {
            DB::beginTransaction();

            $invoices = Invoice::where('customer_id', auth()->id())->whereNotIn('current_status', ['denied', 'canceled', 'done'])->get();
            if (! $invoices) {
                DB::rollBack();
                $data = $this->apiResponse(false, 'Sedang ada transaksi sampah yang belum selesai!');

                return  response()->json($data, 403);
            }

            $withdrawals = Withdrawal::where('customer_id', auth()->id())->whereNotIn('current_status', ['denied', 'canceled', 'done'])->get();
            if (! $withdrawals) {
                DB::rollBack();
                $data = $this->apiResponse(false, 'Masih ada permintaan penarikan saldo Anda yang belum selesai!');

                return  response()->json($data, 403);
            }

            if (auth()->user()->ubahPartner($request->partner_id)) {
                Notification::create([
                    'title' => 'Customer Baru!',
                    'detail' => auth()->user()->name.' ingin Anda menjadi partnernya! Terima?',
                    'link' => route('app.partner.profile.customers.show', ['customer' => auth()->id()]),
                    'broadcasted_to' => $request->partner_id,
                ]);

                $partner = User::findOrFail($request->partner_id);

                $partner = [
                    'name' => $partner->name,
                    'address' => $partner->address,
                    'schedules' => implode(', ', $partner->schedules_converted),
                ];

                DB::commit();
                $data = $this->apiResponse(true, 'OK', $partner);
                $http_code = 200;
            } else {
                DB::rollBack();
                $data = $this->apiResponse(false);
                $http_code = 404;
            }
        } catch (Exception $e) {
            DB::rollBack();
            // $data = $this->apiResponse(false, $e->getMessage());
            $data = $this->apiResponse(false, 'Terjadi masalah pada sistem, harap hubungi penyedia layanan Anda!');
            $http_code = $e->getCode() == 422 ? 422 : 421;
        } catch (Error $e) {
            DB::rollBack();
            // $data = $this->apiResponse(false, $e->getMessage());
            $data = $this->apiResponse(false, 'Terjadi masalah pada sistem, harap hubungi penyedia layanan Anda!');
            $http_code = $e->getCode() == 422 ? 422 : 421;
        }

        return  response()->json($data, $http_code);
    }
}

resources/views/app/customer/withdrawals/create.blade.php
@extends('layout.app.main', ['title' => 'Tarik Tunai', 'back' => route('app.customer.home')])

@section('contents')
    <x-app-card style="border: 2px solid #27AE60 !important">
        <p class="pb-0 mb-0 opacity-80 text-dark fw-bold">Saldo Anda</p>
        <div class="fw-bold font-25 text-dark mb-0">{{ Sirius::toRupiah(auth()->user()->balance) }}</div>
    </x-app-card>

    <x-app-form method="post" id="form-create">
        <div class="bg-white py-3 px-4">
            <div class="d-flex justify-content-between align-items-end">
                <p class="pb-0 mb-0 font-15 opacity-80">Nominal</p>
                <x-app-button color="bg-dark-dark" size="s" icon="fa-solid fa-clock-rotate-left" link="{{ route('app.customer.withdrawals.index') }}">Riwayat</x-app-button>
            </div>
            <div class="d-flex justify-content-between align-items-end gap-1 my-2">
                <div class="h1 fw-bold font-35 text-dark mb-0">Rp</div>
                <div class="input-style no-borders no-icon w-100">
                    <input name="nominal" class="form-control border-0 font-35 fw-bold to-rupiah" value="0">
                </div>
                <div class="h1 fw-bold font-35 text-dark mb-0">,-</div>
            </div>
        </div>
        <div class="bg-white py-4 my-3 px-4">
            <p class="pb-0 mb-0 font-15 opacity-80">Pilih Nominal</p>
            <div class="row mb-0">
                <div class="col-6 fw-bold my-2">
                    <div class="d-flex justify-content-between align-items-content border rounded rounded-5 px-2 py-1" @if(auth()->user()->balance < 50000) style="background-color: var(--bs-gray-300)" @endif>
                        <div class="form-check icon-check mb-0 me-0">
                            <label for="Rp50" class="@if(auth()->user()->balance < 50000) text-gray @else text-dark @endif font-20 pb-0 mb-0">Rp50.000</label>
                            <input class="form-check-input" type="radio" name="selected_nominal" value="50000" id="Rp50" @disabled(auth()->user()->balance < 50000)>
                            <i class="icon-check-1 far fa-circle color-gray-dark font-16"></i>
                            <i class="icon-check-2 far fa-check-circle font-16 color-green-dark"></i>
                        </div>
                    </div>
                </div>
                <div class="col-6 fw-bold my-2">
                    <div class="d-flex justify-content-between align-items-content border rounded rounded-5 px-2 py-1" @if(auth()->user()->balance < 100000) style="background-color: var(--bs-gray-300)" @endif>
                        <div class="form-check icon-check mb-0 me-0">
                            <label for="Rp100" class="@if(auth()->user()->balance < 100000) text-gray @else text-dark @endif font-20 pb-0 mb-0">Rp100.000</label>
                            <input class="form-check-input" type="radio" name="selected_nominal" value="100000" id="Rp100" @disabled(auth()->user()->balance < 100000)>
                            <i class="icon-check-1 far fa-circle color-gray-dark font-16"></i>
                            <i class="icon-check-2 far fa-check-circle font-16 color-green-dark"></i>
                        </div>
                    </div>
                </div>
                <div class="col-6 fw-bold my-2">
                    <div class="d-flex justify-content-between align-items-content border rounded rounded-5 px-2 py-1" @if(auth()->user()->balance < 150000) style="background-color: var(--bs-gray-300)" @endif>
                        <div class="form-check icon-check mb-0 me-0">
                            <label for="Rp150" class="@if(auth()->user()->balance < 150000) text-gray @else text-dark @endif font-20 pb-0 mb-0">Rp150.000</label>
                            <input class="form-check-input" type="radio" name="selected_nominal" value="150000" id="Rp150" @disabled(auth()->user()->balance < 150000)>
                            <i class="icon-check-1 far fa-circle color-gray-dark font-16"></i>
                            <i class="icon-check-2 far fa-check-circle font-16 color-green-dark"></i>
                        </div>
                    </div>
                </div>
                <div class="col-6 fw-bold my-2">
                    <div class="d-flex justify-content-between align-items-content border rounded rounded-5 px-2 py-1" @if(auth()->user()->balance < 200000) style="background-color: var(--bs-gray-300)" @endif>
                        <div class="form-check icon-check mb-0 me-0">
                            <label for="Rp200" class="@if(auth()->user()->balance < 200000) text-gray @else text-dark @endif font-20 pb-0 mb-0">Rp200.000</label>
                            <input class="form-check-input" type="radio" name="selected_nominal" value="200000" id="Rp200" @disabled(auth()->user()->balance < 200000)>
                            <i class="icon-check-1 far fa-circle color-gray-dark font-16"></i>
                            <i class="icon-check-2 far fa-check-circle font-16 color-green-dark"></i>
                        </div>
                    </div>
                </div>
                <div class="col-6 fw-bold my-2">
                    <div class="d-flex justify-content-between align-items-content border rounded rounded-5 px-2 py-1" @if(auth()->user()->balance < 250000) style="background-color: var(--bs-gray-300)" @endif>
                        <div class="form-check icon-check mb-0 me-0">
                            <label for="Rp250" class="@if(auth()->user()->balance < 250000) text-gray @else text-dark @endif font-20 pb-0 mb-0">Rp250.000</label>
                            <input class="form-check-input" type="radio" name="selected_nominal" value="250000" id="Rp250" @disabled(auth()->user()->balance < 250000)>
                            <i class="icon-check-1 far fa-circle color-gray-dark font-16"></i>
                            <i class="icon-check-2 far fa-check-circle font-16 color-green-dark"></i>
                        </div>
                    </div>
                </div>
                <div class="col-6 fw-bold my-2">
                    <div class="d-flex justify-content-between align-items-content border rounded rounded-5 px-2 py-1" @if(auth()->user()->balance < 300000) style="background-color: var(--bs-gray-300)" @endif>
                        <div class="form-check icon-check mb-0 me-0">
                            <label for="Rp300" class="@if(auth()->user()->balance < 300000) text-gray @else text-dark @endif font-20 pb-0 mb-0">Rp300.000</label>
                            <input class="form-check-input" type="radio" name="selected_nominal" value="300000" id="Rp300" @disabled(auth()->user()->balance < 300000)>
                            <i class="icon-check-1 far fa-circle color-gray-dark font-16"></i>
                            <i class="icon-check-2 far fa-check-circle font-16 color-green-dark"></i>
                        </div>
                    </div>
                </div>
                <div class="col-6 fw-bold my-2">
                    <div class="d-flex justify-content-between align-items-content border rounded rounded-5 px-2 py-1" @if(auth()->user()->balance < 350000) style="background-color: var(--bs-gray-300)" @endif>
                        <div class="form-check icon-check mb-0 me-0">
                            <label for="Rp350" class="@if(auth()->user()->balance < 350000) text-gray @else text-dark @endif font-20 pb-0 mb-0">Rp350.000</label>
                            <input class="form-check-input" type="radio" name="selected_nominal" value="350000" id="Rp350" @disabled(auth()->user()->balance < 350000)>
                            <i class="icon-check-1 far fa-circle color-gray-dark font-16"></i>
                            <i class="icon-check-2 far fa-check-circle font-16 color-green-dark"></i>
                        </div>
                    </div>
                </div>
                <div class="col-6 fw-bold my-2">
                    <div class="d-flex justify-content-between align-items-content border rounded rounded-5 px-2 py-1" @if(auth()->user()->balance < 400000) style="background-color: var(--bs-gray-300)" @endif>
                        <div class="form-check icon-check mb-0 me-0">
                            <label for="Rp400" class="@if(auth()->user()->balance < 400000) text-gray @else text-dark @endif font-20 pb-0 mb-0">Rp400.000</label>
                            <input class="form-check-input" type="radio" name="selected_nominal" value="400000" id="Rp400" @disabled(auth()->user()->balance < 400000)>
                            <i class="icon-check-1 far fa-circle color-gray-dark font-16"></i>
                            <i class="icon-check-2 far fa-check-circle font-16 color-green-dark"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="py-3 px-4">
            <x-app-button type="submit" icon='fa-solid fa-credit-card' class="w-100">Tarik</x-app-button>
        </div>
    </x-app-form>
@endsection

@push('js')
    <script>
        function documentReady() {
            $("input[name='selected_nominal']").change(function() {
                $("input[name='nominal']").val(ToRupiah.format($(this).val()).replace('Rp\u00A0', ''))
            })

            $("input[name='nominal']").keyup(function() {
                $("input:radio").prop("checked", false);
            })

            $("#form-create").submit(function(e) {
                e.preventDefault()
                loadingWithText('Mengirim pengajuan ...')

                const data = new FormData(document.getElementById('form-create'));

                ajaxPost("{{ route('app.customer.withdrawals.store') }}", data, null, function (result) {
                    Swal.fire({
                        title: "Permintaan diajukan!",
                        icon: "success",
                    })

                    let withdrawal = result.data
                    setTimeout(() => {
                        window.location.href = "{{ route('app.customer.withdrawals.show', ['withdrawal' => '-code-']) }}".replace('-code-', withdrawal)
                    }, 1000);
                }, function (error) {
                    Swal.fire({
                        title: "Pengajuan gagal!",
                        icon: 'error',
                        text: error.message
                    })
                }, false)
            })
        }
    </script>
@endpush

resources/views/app/customer/withdrawals/index.blade.php
@extends('layout.app.main', ['title' => 'Riwayat Tarikan', 'back' => route('app.customer.withdrawals.create')])

@section('contents')
    @php
        $orders = [
            'code' => 'Kode',
            'amount' => 'Nominal',
            'created_at' => 'Tanggal',
            'current_status' => 'Status'
        ];

        $data = ['code', 'amount', 'status', 'statusColor', 'date']
    @endphp

    <x-app-listing id="listing" name="Riwayat penarikan" :orders="$orders" :route="route('app.customer.withdrawals.index')" :data="$data" sort="desc">
        @slot('skeleton')
            <div class="card rounded-m" style="padding: 20px 15px 20px 15px!important">
                <div class="d-flex justify-content-between align-items-center mb-0">
                    <p class="m-1 w-75">skeleton</p>
                    <p class="m-1 w-25">skeleton</p>
                </div>
                <p class="m-1">skeleton</p>
                <p class="m-1">skeleton</p>
                <p class="m-1 p-2">skeleton</p>
            </div>
        @endslot

        <a href="{{ route('app.customer.withdrawals.show', ['withdrawal' => '[[code]]']) }}">
            <x-app-card class="mb-3">
                <div class="d-flex justify-content-between align-items-center mb-0">
                    <p class="fw-bold font-15 mb-0">Permintaan #[[code]]</p>
                    <p class="fw-bold opacity-70">[[date]]</p>
                </div>
                <p class="mb-0 fw-bold text-[[statusColor]]">[[status]]</p>
                <p class="mb-0 text-center">Total Tunai</p>
                <p class="fw-bold text-center font-20">[[amount]]</p>
            </x-app-card>
        </a>
    </x-app-listing>
@endsection

@push('js')
    <script>
        function documentReady() {
            listingReady()
        }
    </script>
@endpush