routes/web.php
<?php

use App\Http\Controllers\AppNotificationController;
use App\Http\Controllers\AppProfileController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Compro\AboutController;
use App\Http\Controllers\Compro\ArticleController as ComproArticleController;
use App\Http\Controllers\Compro\ContentController as ComproContentController;
use App\Http\Controllers\Compro\PageController as ComproPageController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\Customer\InvoiceController as CustomerInvoiceController;
use App\Http\Controllers\Customer\PartnerController as CustomerPartnerController;
use App\Http\Controllers\Customer\ProductController as CustomerProductController;
use App\Http\Controllers\Customer\WithdrawalController as CustomerWithdrawalController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\Partner\CustomerController as PartnerCustomerController;
use App\Http\Controllers\Partner\InvoiceController as PartnerInvoiceController;
use App\Http\Controllers\Partner\ProductController as PartnerProductController;
use App\Http\Controllers\Partner\ReportController as PartnerReportController;
use App\Http\Controllers\Partner\WithdrawalController as PartnerWithdrawalController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UploaderController;
use App\Http\Controllers\WithdrawalController;
use App\Http\Controllers\SliderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Override Default Auth
Route::get('/login', fn () => redirect(route('app.login')))->name('login');
Route::get('/masuk', fn () => redirect(route('app.login')));
Route::get('/register', fn () => redirect(route('app.register')))->name('register');
Route::get('/daftar', fn () => redirect(route('app.register')));

Route::get('/atur-ulang-kata-sandi/{token}', [AuthController::class, 'resetPasswordView'])->name('password.reset'); //Helper route for fortify
// Admin
Route::group(['prefix' => '/admin', 'as' => 'admin.'], function () {
    Route::get('/masuk', [AuthController::class, 'adminLoginView'])->name('login');

    Route::group(['middleware' => ['auth', 'is_admin']], function () {
        Route::get('/', [DashboardController::class, 'admin'])->name('home');

        Route::group(['prefix' => '/profil', 'as' => 'profile.'], function () {
            Route::get('/', [ProfileController::class, 'index'])->name('index');
            Route::group(['prefix' => '/update', 'as' => 'update.'], function () {
                Route::put('/general', [ProfileController::class, 'updateGeneral'])->name('general');
                Route::put('/password', [ProfileController::class, 'updatePassword'])->name('password');
                Route::put('/avatar', [ProfileController::class, 'updateAvatar'])->name('avatar');
            });
        });

        Route::group(['prefix' => '/master', 'as' => 'master.'], function () {
            Route::get('/customer/search', [CustomerController::class, 'search'])->name('customers.search');
            Route::get('/partner/search', [PartnerController::class, 'search'])->name('partners.search');

            Route::get('customer/download', [CustomerController::class, 'download'])->name('customers.download');
            Route::apiResource('customer', CustomerController::class)->names('customers');
            Route::get('customer/password/generate', [CustomerController::class, 'generatePassword'])->name('customers.password.generate');
            Route::put('customer/password/{customer}', [CustomerController::class, 'updatePassword'])->name('customers.password');

            Route::apiResource('partner', PartnerController::class)->names('partners');
            Route::apiResource('produk', ProductController::class)->names('products');
            Route::apiResource('metode-pembayaran', PaymentMethodController::class)->names('payments');
        });

        Route::group(['prefix' => '/layanan', 'as' => 'services.'], function () {
            Route::apiResource('transaksi', InvoiceController::class)->names('transactions')->only(['index', 'show']);
            Route::apiResource('penarikan-saldo', WithdrawalController::class)->names('withdrawals')->only(['index', 'show']);
        });

        Route::group(['prefix' => '/laporan', 'as' => 'reports.'], function () {
            Route::any('/pengeluaran', [ReportController::class, 'expense'])->name('expenses');
            Route::any('/produk', [ReportController::class, 'product'])->name('products');
        });

        Route::group(['prefix' => '/company-profile', 'as' => 'compro.'], function () {
            Route::group(['prefix' => '/pengaturan', 'as' => 'settings.'], function () {
                Route::get('/', [SettingController::class, 'index'])->name('index');
                Route::group(['prefix' => '/update', 'as' => 'update.'], function () {
                    Route::put('/general', [SettingController::class, 'updateGeneral'])->name('general');
                    Route::put('/total', [SettingController::class, 'updateTotal'])->name('total');
                });
            });

            Route::apiResource('slider', SliderController::class)->names('sliders');
            Route::resource('/konten', ContentController::class)->names('contents')->except('show');
            Route::resource('/artikel', ArticleController::class)->names('articles')->except('show');

            Route::group(['prefix' => '/halaman', 'as' => 'pages.'], function () {
                Route::get('/{page}', [PageController::class, 'edit'])->name('edit');
                Route::put('/{page}', [PageController::class, 'update'])->name('update');
            });
        });
    });
});

// App
Route::group(['prefix' => '/app', 'as' => 'app.'], function () {
    Route::get('/', [DashboardController::class, 'app'])->name('home');
    Route::get('/masuk', [AuthController::class, 'appLoginView'])->name('login');
    Route::get('/daftar', [AuthController::class, 'appRegisterView'])->name('register');
    Route::get('/verifikasi', [AuthController::class, 'appVerifyView'])->name('verify');
    Route::get('/lupa-kata-sandi', [AuthController::class, 'forgotPasswordView'])->name('forgot-password');
    Route::post('/lupa-kata-sandi', [AuthController::class, 'sendRequestPasswordReset'])->name('forgot-password');
    Route::get('/atur-ulang-kata-sandi/{token}', [AuthController::class, 'resetPasswordView'])->name('reset-password');
    Route::put('/atur-ulang-kata-sandi', [AuthController::class, 'resetPassword'])->name('reset-password');

    // Route::get('/reset-password/{token}', function (string $token) {
    //     return view('auth.reset-password', ['token' => $token]);
    // })->middleware('guest')->name('password.reset');

    Route::post('/simpan-device-token', [AuthController::class, 'storeDeviceToken'])->name('store-device-token');
    Route::post('/masuk-otomatis', [AuthController::class, 'sessionLogin'])->name('auto-login');
    Route::view('/offline', 'laravelpwa::offline')->name('offline');

    Route::group(['prefix' => '/pemberitahuan', 'as' => 'notification.'], function () {
        Route::match(['get', 'post'], '/', [AppNotificationController::class, 'index'])->name('index');
        Route::get('/ke/{notification}', [AppNotificationController::class, 'goto'])->name('goto');
    });

    Route::group(['prefix' => '/customer', 'as' => 'customer.', 'middleware' => ['auth', 'is_customer']], function () {
        Route::group(['prefix' => '/konfirmasi-alamat', 'as' => 'address.'], function () {
            Route::get('/', [AppProfileController::class, 'confirmAddress'])->name('confirm');
            Route::put('/', [AppProfileController::class, 'updateAddress'])->name('update');
        });

        Route::group(['middleware' => 'must_fill_address'], function () {
            Route::get('/', [DashboardController::class, 'customer'])->name('home');

            Route::group(['prefix' => '/profil', 'as' => 'profile.'], function () {
                Route::get('/', [AppProfileController::class, 'index'])->name('index');
                Route::get('/ubah', [AppProfileController::class, 'edit'])->name('edit');
                Route::get('/ubah/kata-sandi', [AppProfileController::class, 'editPassword'])->name('password');
                Route::put('/ubah', [AppProfileController::class, 'update'])->name('update');
                Route::put('/ubah/kata-sandi', [AppProfileController::class, 'updatePassword'])->name('password');
            });

            Route::group(['prefix' => '/partner', 'as' => 'partner.'], function () {
                Route::get('/', [CustomerPartnerController::class, 'index'])->name('index');
                Route::post('/nearby', [CustomerPartnerController::class, 'nearby'])->name('nearby');
                Route::post('/change', [CustomerPartnerController::class, 'change'])->name('change');
            });

            Route::group(['middleware' => 'must_connected_with_partner'], function () {
                Route::group(['prefix' => '/produk', 'as' => 'products.'], function () {
                    Route::get('/', [CustomerProductController::class, 'index'])->name('index');

resources/views/admin/index.blade.php
@extends('layout.admin.main', ['title' => 'Dashboard'])

@section('content')
    <div class="d-flex flex-column justify-content-center h-100">
        <div class="row">
            <div class="col-md-4 mb-3">
                <x-admin-card>
                    <div class="d-flex display-5 align-items-center">
                        <div class="p-0 m-0">
                            <i class="bx bxs-user-account"></i>
                        </div>
                        <div class="border-start ps-3 ms-3">
                            {{ $customers }}<br>
                            <small class="h6">Total Customer</small>
                        </div>
                    </div>
                </x-admin-card>
            </div>
            <div class="col-md-4 mb-3">
                <x-admin-card>
                    <div class="d-flex display-5 align-items-center">
                        <div class="p-0 m-0">
                            <i class="bx bxs-user-badge"></i>
                        </div>
                        <div class="border-start ps-3 ms-3">
                            {{ $partners }}<br>
                            <small class="h6">Total Partner</small>
                        </div>
                    </div>
                </x-admin-card>
            </div>
            <div class="col-md-4 mb-3">
                <x-admin-card>
                    <div class="d-flex display-5 align-items-center">
                        <div class="p-0 m-0">
                            <i class="bx bxs-package"></i>
                        </div>
                        <div class="border-start ps-3 ms-3">
                            {{ $products }}<br>
                            <small class="h6">Total Jenis Produk</small>
                        </div>
                    </div>
                </x-admin-card>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <x-admin-card>
                    <div class="d-flex display-5 align-items-center">
                        <div class="p-0 m-0">
                            <i class="bx bx-money"></i>
                        </div>
                        <div class="border-start ps-3 ms-3">
                            {{ Sirius::toRupiah($nominal) }}<br>
                            <small class="h6">Total Nominal Transaksi</small>
                        </div>
                    </div>
                </x-admin-card>
            </div>
            <div class="col-md-6 mb-3">
                <x-admin-card>
                    <div class="d-flex display-5 align-items-center">
                        <div class="p-0 m-0">
                            <i class="bx bx-dumbbell"></i>
                        </div>
                        <div class="border-start ps-3 ms-3">
                            {{ round($weight) }} kg<br>
                            <small class="h6">Total Berat Sampah</small>
                        </div>
                    </div>
                </x-admin-card>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/profile.blade.php
@extends('layout.admin.main', ['title' => 'Profil'])

@push('css')
    <link rel="stylesheet" href="{{ asset('css/dropzone.min.css') }}">
@endpush

@section('content')
    <x-admin-card header="Profil Admin">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Nama
                <x-admin-button size="sm" data-bs-toggle="modal" data-bs-target="#edit-name"><i class="fa-solid fa-edit me-2"></i>Ubah</x-admin-button>
            </li>
            <li class="list-group-item list-group-item-secondary d-flex justify-content-between align-items-center">
                Alamat Email
                <x-admin-button size="sm" data-bs-toggle="modal" data-bs-target="#edit-email"><i class="fa-solid fa-edit me-2"></i>Ubah</x-admin-button>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Kata Sandi
                <x-admin-button size="sm" data-bs-toggle="modal" data-bs-target="#edit-password"><i class="fa-solid fa-edit me-2"></i>Ubah</x-admin-button>
            </li>
            <li class="list-group-item list-group-item-secondary d-flex justify-content-between align-items-center">
                Avatar
                <x-admin-button size="sm" data-bs-toggle="modal" data-bs-target="#edit-avatar"><i class="fa-solid fa-edit me-2"></i>Ubah</x-admin-button>
            </li>
        </ul>
    </x-admin-card>
@endsection

@section('modal')
    <x-admin-modal id="edit-name" title="Ubah Nama">
        <x-admin-form method="put" id="form-name" submit="Simpan Perubahan" submitWide>
            <input type="hidden" name="name" value="name">
            <x-admin-form-input id="form-edit-name" name="value" value="{{ auth()->user()->name }}" required/>
        </x-admin-form>
    </x-admin-modal>

    <x-admin-modal id="edit-email" title="Ubah Alamat Email">
        <x-admin-form method="put" id="form-email" submit="Simpan Perubahan" submitWide>
            <input type="hidden" name="name" value="email">
            <x-admin-form-input id="form-edit-email" name="value" value="{{ auth()->user()->email }}" type="email" required/>
        </x-admin-form>
    </x-admin-modal>

    <x-admin-modal id="edit-password" title="Ubah Kata Sandi">
        <x-admin-form method="put" id="form-password" submit="Simpan Perubahan" submitWide>
            <x-admin-form-input id="form-edit-current-password" name="current_password" type="password" label="Kata Sandi Sebelumnya" class="mb-3" required/>
            <x-admin-form-input id="form-edit-new-password" name="password" type="password" label="Kata Sandi Baru" class="mb-3" required/>
            <x-admin-form-input id="form-edit-new-password-confirmation" name="password_confirmation" type="password" label="Konfirmasi Kata Sandi Baru" class="mb-3" required/>
        </x-admin-form>
    </x-admin-modal>

    <x-admin-modal id="edit-avatar" title="Ubah Avatar">
        <x-admin-form method="put" id="form-avatar" submit="Simpan Perubahan" submitWide>
            <input type="hidden" name="name" value="avatar">
            <x-admin-form-input-file id="form_edit_avatar" name="value" value="{{ auth()->user()->avatar }}" valueSize="{{ auth()->user()->avatar_size }}" formId='form-avatar' accepted="image/*" required/>
        </x-admin-form>
    </x-admin-modal>
@endsection

@push('js')
    <script src="{{ asset('js/dropzone.min.js') }}"></script>
    <script>
        Dropzone.autoDiscover = false;

        $(document).ready(function () {
            $('#form-name').submit(function (e) {
                e.preventDefault()
                loading()

                const data = new FormData(document.getElementById('form-name'));
                ajaxPost("{{ route('admin.profile.update.general') }}", data, "#edit-name")
            })

            $('#form-email').submit(function (e) {
                e.preventDefault()
                loading()

                const data = new FormData(document.getElementById('form-email'));
                ajaxPost("{{ route('admin.profile.update.general') }}", data, "#edit-email")
            })

            $('#form-password').submit(function (e) {
                e.preventDefault()
                loading()

                const data = new FormData(document.getElementById('form-password'));
                ajaxPost("{{ route('admin.profile.update.password') }}", data, "#edit-password")
            })

            $('#form-avatar').submit(function (e) {
                e.preventDefault()
                loading()

                const data = new FormData(document.getElementById('form-avatar'));
                ajaxPost("{{ route('admin.profile.update.avatar') }}", data, "#edit-avatar")
            })
        })
    </script>
@endpush